//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICE
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Local_Date { get; set; }
        public Nullable<int> ShipmentId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<decimal> Price_Unit { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Total_bef_tax { get; set; }
        public Nullable<decimal> Total_aft_tax { get; set; }
        public Nullable<decimal> Taxes { get; set; }
        public Nullable<bool> Paid { get; set; }
    
        public virtual PRODUCT_ORDERS PRODUCT_ORDERS { get; set; }
        public virtual SHIPMENT SHIPMENT { get; set; }
    }
}
