//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IRONMONGERYEntities : DbContext
    {
        public IRONMONGERYEntities()
            : base("name=IRONMONGERYEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DELIVERY> DELIVERies { get; set; }
        public virtual DbSet<INVOICE> INVOICES { get; set; }
        public virtual DbSet<LOGISTIC> LOGISTICS { get; set; }
        public virtual DbSet<NOTICE> NOTICES { get; set; }
        public virtual DbSet<ORDER> ORDERS { get; set; }
        public virtual DbSet<PRODUCT_ORDERS> PRODUCT_ORDERS { get; set; }
        public virtual DbSet<PRODUCT> PRODUCTS { get; set; }
        public virtual DbSet<SERVICE_ORDERS> SERVICE_ORDERS { get; set; }
        public virtual DbSet<SERVICE> SERVICES { get; set; }
        public virtual DbSet<SHIPMENT> SHIPMENTS { get; set; }
        public virtual DbSet<TRUCK> TRUCKs { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<WAREHOUSE> WAREHOUSEs { get; set; }
    }
}
