//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTICE
    {
        public int Id { get; set; }
        public Nullable<int> ShipmentID { get; set; }
        public Nullable<System.TimeSpan> Local_Time { get; set; }
        public Nullable<int> ProductId { get; set; }
    
        public virtual PRODUCT_ORDERS PRODUCT_ORDERS { get; set; }
        public virtual SHIPMENT SHIPMENT { get; set; }
    }
}
