//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.PRODUCT_ORDERS = new HashSet<PRODUCT_ORDERS>();
        }
    
        public int Id { get; set; }
        public string Product_Name { get; set; }
        public string Category { get; set; }
        public string Product_Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Units { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT_ORDERS> PRODUCT_ORDERS { get; set; }
    }
}
