//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHIPMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SHIPMENT()
        {
            this.DELIVERies = new HashSet<DELIVERY>();
            this.INVOICES = new HashSet<INVOICE>();
            this.NOTICES = new HashSet<NOTICE>();
        }
    
        public int Id { get; set; }
        public Nullable<int> SellerID { get; set; }
        public Nullable<int> Product_Order { get; set; }
        public Nullable<int> Service_Order { get; set; }
        public Nullable<int> TruckID { get; set; }
        public Nullable<System.TimeSpan> Order_Time { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELIVERY> DELIVERies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVOICE> INVOICES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTICE> NOTICES { get; set; }
        public virtual PRODUCT_ORDERS PRODUCT_ORDERS { get; set; }
        public virtual SERVICE_ORDERS SERVICE_ORDERS { get; set; }
        public virtual USER USER { get; set; }
    }
}
