//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAREHOUSE
    {
        public int Id { get; set; }
        public Nullable<System.TimeSpan> EntryTime { get; set; }
        public Nullable<int> TruckId { get; set; }
        public Nullable<System.TimeSpan> ExitTime { get; set; }
    
        public virtual LOGISTIC LOGISTIC { get; set; }
    }
}
